name: test-parse

on:
  [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ci
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --dev
      - run: npm run build
      - run: node ./runTest.js